name: 'Run unit tests'
description: 'Run the unit tests for a given Python version'

inputs:
  python-version:
    description: 'Python version to use'
    default: 3.7.12
    required: false
  poetry-version:
    description: 'Poetry version to use'
    default: 1.1.12
    required: false
  test-report-file:
    description: 'File name to save the test report in'
    required: true

runs:
  using: "composite"

  steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - uses: snok/install-poetry@v1
        with:
          version: ${{ inputs.poetry-version }}
          virtualenvs-in-project: true

      - name: Check cache
        id: cached-poetry
        uses: actions/cache@v2
        with:
          path: .venv
          key: unit-${{ hashFiles('poetry.lock') }}-${{ inputs.python-version }}-1

      - name: Install dependencies
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        run: poetry install --no-interaction

      - name: Run tests
        run: |
          source .venv/bin/activate
          python -m pytest tests --verbose --junitxml=${{ inputs.test-report-file }}

      - name: Upload report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ inputs.test-report-file }}
          path: ${{ inputs.test-report-file }}
