name: 'Run unit tests'
description: 'Run the unit tests for a given Python version'

inputs:
  python-version:
    description: 'Python version to use'
    default: 3.8.18
    required: false
  pydantic-version:
    description: 'Pydantic version to use'
    default: ''
    required: false
  test-report-file:
    description: 'File name to save the test report in'
    required: true

runs:
  using: "composite"

  steps:
      - name: Setup uv environment
        uses: ./.github/actions/setup-uv-environment
        with:
          python-version: ${{ inputs.python-version }}
          with-dev-dependencies: true

      - name: Override pydantic version
        if: ${{ inputs.pydantic-version }}
        run: uv pip install pydantic==${{ inputs.pydantic-version }}
        shell: bash

      - name: Run tests
        run: |
          source .venv/bin/activate
          uv run python -m pytest tests --verbose --junitxml=${{ inputs.test-report-file }}
        shell: bash

      - name: Upload report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ inputs.test-report-file }}
          path: ${{ inputs.test-report-file }}
