name: "Setup build environment"
description: "Sets up Python, UV and dependencies"

inputs:
  python-version:
    description: "Python version to use"
    default: 3.8.18
    required: false
  uv-version:
    description: "UV version to use"
    default: 0.7.12
    required: false

runs:
  using: "composite"

  steps:
    - name: Set up python
      uses: useblacksmith/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@v6
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: "false"
#        cache-dependency-glob: |
#          **/pyproject.toml
#          **/uv.lock

    - id: cached-uv
      uses: useblacksmith/cache@v5
      with:
        path: .venv
        key: ${{ runner.os }}-${{ runner.arch }}-${{ inputs.python-version }}-uv-${{ hashFiles('uv.lock', 'pyproject.toml') }}


    - name: Create virtual environment and install dependencies on cache miss
#      if: steps.setup-uv.outputs.cache-hit != 'true'
      if: steps.cached-uv.outputs.cache-hit != 'true'
      run: |
#        uv venv --python ${{ inputs.python-version }}
        uv sync --frozen
      shell: bash

    - name: Active virtual environment
      run: |
        echo "VIRTUAL_ENV=.venv" >> $GITHUB_ENV
      shell: bash
