#!/usr/bin/env python3

import json
from pathlib import Path

link_file = Path("./source/links.json")
with link_file.open('r') as f:
    links = json.load(f)

keys = list(links.keys())
texts = [links[k]["user_text"] for k in keys]
urls = [links[k]["url"] for k in keys]

user_text = input("What should the link title be?\n")
key = "_".join(user_text.lower().split())  # Lower snake case
url = input("What is the associated url?\n")

if key in links:
    raise ValueError(
        f"Key `{key}` already exists with title `{links[key]['user_text']}` and "
        f"url `{links[key]['url']}`."
    )

if url in urls:
    idx = urls.index(url)
    raise ValueError(
        f"Url `{url}` already exists with title `{texts[idx]}` and "
        f"key `{keys[idx]}`."
    )

links[key] = {'user_text': user_text, 'url': url}

with link_file.open('w') as f:
    json.dump(links, f, indent=2)

print(f"Successfully added link to list with key {key}")
