#!/usr/bin/env bash

set -e

echo "Isort"
# isort ./**/*.py --profile black --line-length 60
poetry run isort . --resolve-all-configs

echo "Black"
poetry run black --config=source/code_examples/pyproject.toml .

poetry run make clean
poetry run make html
