#!/usr/bin/env bash

set -e

source $(poetry env info --path)/bin/activate

echo "Isort"
# isort ./**/*.py --profile black --line-length 60
isort . --profile black --line-length 60

echo "Black"
black . --include ".*\.py" --line-length 60

make html
