name: "Send Slack notification"
description: "Send Slack message on success/failure parameter"

inputs:
  success-parameter:
    description: "Pass success or failure here"
    required: true
  success-channel:
    description: "Channel ID for sending success notifications"
    required: false
    default: ''
  failure-channel:
    description: "Channel ID for sending failure notifications"
    required: false
    default: ''
  success-message:
    description: "Message body on success"
    required: false
    default: ''
  failure-message:
    description: "Message body on failure"
    required: false
    default: 'This pipeline has failed!'

runs:
  using: "composite"

  steps:
    - id: commit-message
      run: |
        echo "${{ github.event.head_commit.message }}" > message.txt
        sed -z 's/\n/\\n/g' message.txt > newmessage.txt
        echo "message=$(cat newmessage.txt)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: slackapi/slack-github-action@v1.18.0
      if: inputs.success-parameter == 'success' && inputs.success-channel != ''
      with:
        channel-id: ${{ inputs.success-channel }}
        payload: |
          {
            "text": "Success",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":white_check_mark: Success: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{ github.workflow }}>\n:memo: Commit: <${{ github.event.head_commit.url }}|${{ github.ref_name }}>\n:hatching_chick: What's new: ${{ steps.commit-message.outputs.message }}\n\n${{ inputs.success-message }}"
                }
              }
            ]
          }

    - uses: slackapi/slack-github-action@v1.18.0
      if: inputs.success-parameter == 'failure' && inputs.failure-channel != ''
      with:
        channel-id: ${{ inputs.failure-channel }}
        payload: |
          {
            "text": "Failure",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":exclamation: FAILURE: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|${{ github.workflow }}>\n:memo: Commit: <${{ github.event.head_commit.url }}|${{ github.ref_name }}>\n:beetle: Issue: ${{ steps.commit-message.outputs.message }}\n\n${{ inputs.failure-message }}"
                }
              }
            ]
          }
