on:
  schedule:
    - cron: '00 11 * * *'
  workflow_dispatch:
name: Aikido Scan
jobs:
  aikido-local-scan-repo:
    runs-on: ubuntu-latest
    container:
      image: aikidosecurity/local-scanner:v1.0.52
    steps:
      - uses: actions/checkout@v4
      - name: Run scan
        run: aikido-local-scanner scan ./ --apikey ${{ secrets.AIKIDO_API_Key }} --repositoryname enncord-client-python --branchname master
